# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jade Chan
email: jadechancyj907@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Crave for knowledge and fun
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cyj907.github.io" # the base hostname & protocol for your site
twitter_username: cyj907
github_username:  cyj907

# Build settings
markdown: redcarpet
theme: tale
permalink: /:year-:month-:day/:title
paginate: 10
